"""更新新闻分类是否删除字段

Revision ID: 784de412ac5c
Revises: a8caa0245328
Create Date: 2022-02-27 13:14:38.388030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784de412ac5c'
down_revision = 'a8caa0245328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_category', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_category', 'status')
    # ### end Alembic commands ###
