# 图片验证码 Redis 有效期，单位L秒
IMAGE_CODE_REDIS_EXPIRES = 30000

# 短信验证码redis有效期，单位：秒
SMS_CODE_REDIS_EXPIRES = 30000

# 七牛云链接地址
QINIU_DOMAIN_PREFIX = ''

HOME_PAE_MAX_NEWS = 10

USER_FOLLOW_MAX_COUNT = 4

OTHER_NEWS_PAGE_MAX_COUNT = 10

CLICK_RANK_MAX_NEWS = 10

ADMIN_USER_PAGE_MAX_COUNT = 10

ADMIN_NEWS_PAGE_MAX_COUNT = 10

